### ISSUE TITLE
Fractal Combat X fails at license check

### ISSUE THREAD

**Issue by freakdave** [ouya-saviors/ouya-game-data#101]
I can't get Fractal Combat X to launch properly due to a failing license check.
The OUYA plain purchases module [1.1.0] for xposed is installed.

Here's what happens when i hit PLAY:
![image](https://user-images.githubusercontent.com/1956101/97375251-9fdd5b80-18ba-11eb-9332-a8b8936f43c2.png)
![image](https://user-images.githubusercontent.com/1956101/97375259-a8ce2d00-18ba-11eb-8139-d81873e1345d.png)
The game will quit to the launcher after confirming the message.

**Comment by cweiske** [comment]
com.oyatsukai.fractalcombatxpremium
http://ouya.cweiske.de/game/com.oyatsukai.fractalcombatxpremium.htm

**Comment by cweiske** [comment]
Works on my test server:
```
I/oyatsukai( 1362): (1)PRINT  : OUYA purchase confirmed: fcx_purchase
I/oyatsukai( 1362): (1)PRINT  : OUYA licensed
I/oyatsukai( 1362): (1)PRINT  : license validated
I/oyatsukai( 1362): (1)PRINT  : enabled native
```

**Comment by cweiske** [comment]
@freakdave Make sure you are using my server (ouya.cweiske.de)
