### ISSUE TITLE
more JRLS games

### ISSUE THREAD

**Issue by cweiske** [ouya-saviors/ouya-game-data#106]
> 14:05 JRLS: hi @szeraax , here are the two games (Venture, and UFO) that can be added to the discover store (the UFO game is the same you had last time, but here it is again) : http://jrxs.net/ouya/Venture_[10.5.2020]_OUYA.zip  and http://jrxs.net/ouya/UFO_[3.4.2020]_OUYA.zip . The zip contains the .apk (with ouya_icon in the .apk) but also as separate file,  screenshots (in 1280x720 png and jpg), and the descriptions. Thanks :slight_smile:

**Comment by JRLS** [comment]
i forgot the tags of these games:
UFO : retro, arcade/pinball
Venture : retro , arcade/pinball, fps/shooter, adventure

**Comment by JRLS** [comment]
these games are from developer "Scorpion Software" (me)
 http://ouya.cweiske.de/discover/dev--041c1942-4c52-41b8-9d3b-3f0619284313.htm
