### ISSUE TITLE
Idea : 'more from developer' in the discover store

### ISSUE THREAD

**Issue by JRLS** [ouya-saviors/ouya-game-data#108]
the old discover store had an option to see more games from a developer.
if you open a game, you also have the option 'games'.
when clicked you see more games from this developer. Like a discover with only this developer filtered
i think it's a great idea to add the option to the new discover store!

http://www.jrxs.net/ouya/games.jpg

**Comment by cweiske** [comment]
That screenshot is most probably from me when I was experimenting with additional buttons.

But I found actual screenshots of that extra button, "DEVELOPER PAGE" between "Favorite" and "uninstall": 
- https://androidcommunity.com/ouya-chupacabra-system-update-brings-in-xbmc-audio-passthrough-and-revamped-pages-20140416/
- https://youtu.be/-o6d4769EBs?t=546

**Comment by JRLS** [comment]
you're right! 'developer page' , that was it!
i didnt remember correctly!, good job finding that picture
if you click it, you just see the game tile with games. It look a bit like the normal discover page, but just 1 dev selected
but, you like the idea, right? I think it would be a very handy addition :)

**Comment by cweiske** [comment]
I doubt that the developer detail page was just like a discover category. I'd really like to see a screenshot of such an original page.

**Comment by JRLS** [comment]
no, i dont mean discover category, 
i looks like the game panes you see in the discover page, but just on one screen
i can vaguely remember how it looked, but havent found a screenshot yet
i can make a mockup on how i remember it looked

**Comment by cweiske** [comment]
The feature was introduced in "OUYA System Update “Chupacabra” – Apr 16, 2014" http://web.archive.org/web/20190528141654/https://www.ouya.tv/ouya-system-update-chupacabra-apr-15-2014/:

> Added Developer-specific Details pages (and support for other generic Details pages).
> Now you can learn more about the folks who make the great games you love. Get to know your favorite devs!
> These pages also allow an easy way to access all the games from a specific developer.
> As Developers fill out their profiles, you’ll start to see these pages appear on the console.

Another screenshot of a game detail page with "Developer page" link: http://web.archive.org/web/20190529232931im_/https://www.ouya.tv/wp-content/uploads/2014/04/newDetailsPage-1024x576.png

**Comment by cweiske** [comment]
Implemented:
- Game details linking to developer page: http://ouya.cweiske.de/game/com.scorpion.Laosquest.htm
- Developer games page: http://ouya.cweiske.de/discover/dev--041c1942-4c52-41b8-9d3b-3f0619284313.htm

**Comment by JRLS** [comment]
AWESOME! good work!
