### ISSUE TITLE
Idea : add "New" or "Latest" to discover store

### ISSUE THREAD

**Issue by JRLS** [ouya-saviors/ouya-game-data#109]
currently there is a "last updated" category, which seems to hold new games as well as games that were already on the store, but where updated.

Is it an idea to add a category "New" or "Latest" which contains the last 10 (or 20) NEW games (so not updated ones).

the category "last updated" should then only contain updates games, and not also new games.

**Comment by cweiske** [comment]
I wonder what meta data we could use to determine when a game is new. Maybe the date of the first apk version?

**Comment by JRLS** [comment]
you could show the latest games with the youngest date.

something like this, just an idea:
new : 
1- pick all the games which have only one .apk version at the moment
2-pick the 10 games with the youngest date

because, if a game has more that one .apk version, then it must have been updated, so it goes into the 'latest update' category

**Comment by JRLS** [comment]
i'm not sure if your database holds al the different version information somewhere (not the .apk, but just the version info)

**Comment by JRLS** [comment]
ok, just checked the json files in ouya-game-data/classic/.
the node 'releases' holds all the version numbers, so it's possible to know if a game is new (only 1 apk), and the date is known, so you can know how new it is.

**Comment by JRLS** [comment]
i would also expend the list of "last update" or "new" to a lot more items.
i think it now shows a list of the latest 10 games. Maybe expand that to 75 or something?

**Comment by cweiske** [comment]
Fixed. http://ouya.cweiske.de/discover/
