### ISSUE TITLE
Discover store does not seem to use the ouya_icon.png for every game

### ISSUE THREAD

**Issue by JRLS** [ouya-saviors/ouya-game-data#110]
on the discover store i browse through the games, and put the cursor on my game 'shoot out!' (from the gamejam category).
I'm not clicking it, just highlighting it.

But it is not showing the ouya_icon.png on the discover screen, 
instead it's showing one of the screenshots.

Before the jam category, i sideloaded the game. and then it IS showing the ouya_icon.png

**Comment by cweiske** [comment]
I probably did not find the ouya_icon file when I added the game to this repository, and used the screenshot as fallback.

http://ouya.cweiske.de/game/com.scorpion.shootout.htm

**Comment by JRLS** [comment]
You mean, i did not find it automatically or by hand?

Anyway, the .apk contains res\drawable-xhdpi-v4\ouya_icon.png
Maybe, some other .apk dont have a "-v4" at the end of the foldername?
Just saying, as it might be a problem when adding other .apks? (just a thought)

anyway, you fixed it :) thanks :)
