### ISSUE TITLE
ePSXe missing

### ISSUE THREAD

**Issue by cweiske** [ouya-saviors/ouya-game-data#126]
An PSX emulator
https://archive.org/details/ouya_com.epsxe.ePSXe_1.9.17

Website: http://www.epsxe.com/ and http://www.epsxe.com/android/index.html
It was never on the official games list: http://web.archive.org/web/20160623213930/https://www.ouya.tv/games/
There were requests, but no official responses for releasing on the ouya store:
- https://www.ngemu.com/threads/ouya-release.158956/
- https://www.ngemu.com/threads/ouya-is-epsxe-coming.154678/

The .apk does not have an ouya icon, and I guess it does not appear in the play menu.

Category: Repackaged

**Comment by cweiske** [comment]
Listed in #38.

**Comment by cweiske** [comment]
I can confirm: Does not appear in the play menu.

**Comment by ZacharyFoxx** [comment]
Do you want a repackaged apk of this version or could it be from a newer version?

**Comment by cweiske** [comment]
Could be a newer one.

**Comment by ZacharyFoxx** [comment]
> Could be a newer one.

I will do it.

**Comment by ZacharyFoxx** [comment]
Pull request done!

**Comment by cweiske** [comment]
Where did you get that version from?

**Comment by cweiske** [comment]
@ZacharyFoxx Please convert the discover image from .png to .jpg. The file size should be much smaller then.

**Comment by ZacharyFoxx** [comment]
> Where did you get that version from?

I bought the ePSXe a long time ago when it had a promotion on the Google Store. This version doesn't have any patches or cracks, I just created an icon for OUYA, changed the AndroiManifest.xml and re-signed it.
