### ISSUE TITLE
Add Spelunky Classic

### ISSUE THREAD

**Issue by cweiske** [ouya-saviors/ouya-game-data#132]
xaby says it works on ouya.

Need to check if it appears on the play menu and has a proper icon.

- https://yancharkin.itch.io/spelunky-classic-hd
- https://github.com/yancharkin/SpelunkyClassicHD

**Comment by cweiske** [comment]
@nachoz12341 any progress?

**Comment by dtgreene** [comment]
@cweiske I just tried running it and it boots up correctly but the controls don't seem to work.  Using the touchpad to interact with the on-screen controls work but it's not really playable.

**Comment by cweiske** [comment]
Then we'll close the issue here since there is no progress.

Thanks for the test @dtgreene .

**Comment by nachoz12341** [comment]
Message me on the discord server and we can take a look at the controller issues
