### ISSUE TITLE
Final Fantasy 3 does not work

### ISSUE THREAD

**Issue by cweiske** [ouya-saviors/ouya-game-data#152]
[Final Fantasy III](https://ouya.cweiske.de/game/com.square_enix.android_OUYA.FFIII.htm) always stays in demo mode and does not unlock, neither with nor without the [plain purchases module](https://github.com/cweiske/xposed-ouya-plain-purchases/). Does not work when XPosed is enabled.

Previous work on that issue:
- http://cweiske.de/tagebuch/square-enix-securityexception.htm

From chat:
> kgal: So I did some searching and saw that it still seemed to be an unsolved issue, and I couldn't find this link when searching the discord, but the ff3 port for vitaay be a lead for fixing the checks causing it to not work still on ouya. https://github.com/frangarcj/ff3_vita

**Comment by ZacharyFoxx** [comment]
Did you already had it installed and only now changed the ouya plain purchase or you changed the ouya plain purchased and after that installed the FF3?

I did a hard reset on OUYA, installing the factory firmware.

After rooting I installed the Xposed framework and ouya plain purchase, and before install Xposed framework in system through its menu, I changed the ouya plain purchase to a system apk.

After this I purchased the FF3 and it doesn't show any purchase option on menu to me.

**Comment by cweiske** [comment]
I had plain purchases already installed and activated and only moved it to the new location.
FF3 was installed after I moved plain purchases.

I've got to test if the module works at all. maybe i have to re-enable the it.

**Comment by ZacharyFoxx** [comment]
> I had plain purchases already installed and activated and only moved it to the new location. FF3 was installed after I moved plain purchases.
> 
> I've got to test if the module works at all. maybe i have to re-enable the it.

I would have no problem redoing the process. What would you like me to capture in each step and how to capture it?

**Comment by cweiske** [comment]
It worked after disabling the module, rebooting, enabling and rebooting.

We learned: Converting an already enabled plain purchases module into system does not work.

**Comment by cweiske** [comment]
- I've added instructions to fix it on my blog: http://cweiske.de/tagebuch/ouya-final-fantasy3.htm#howto
- the FF3 game page links to the instructions: https://ouya.cweiske.de/game/com.square_enix.android_OUYA.FFIII.htm
- the plain purchases page also links to it: http://stouyapi.cwboo/game/de.cweiske.ouya.plainpurchases.htm
