### ISSUE TITLE
Latest release

### ISSUE THREAD

**Issue by Szeraax** [ouya-saviors/ouya-game-data#158]
Which release is the latest for this game? The one with the highest VersionCode? Name? Date? Largest size? 

https://github.com/ouya-saviors/ouya-game-data/blob/master/classic/com.realtechvr.nogravity.json

**Comment by Szeraax** [comment]
I always assume that it is the one with the highest VersionCode , since Android won't let install an APK that has a lower VersionCode number.

**Comment by cweiske** [comment]
You cannot update an existing application with an .apk that has a lower versionCode.

We have either versionCode or date to choose from, and I lean towards using the date.

**Comment by cweiske** [comment]
but versionCode is programmatically correct.
