### ISSUE TITLE
Error on booting up Ultionus: A Tale of Petty Revenge

### ISSUE THREAD

**Issue by Stories8106** [ouya-saviors/ouya-game-data#16]
On cweiske's server, see attached screen grab
![Ultionus Bug](https://user-images.githubusercontent.com/26497422/72222344-a3714300-3531-11ea-8cb3-4e3e807e453e.png)

**Comment by cweiske** [comment]
logcat says:
> D/HTTP    (  580): Response 44: GET /api/v1/developers/dc1e924e-5aa1-405b-beb5-de435ae7e88f/current_gamer?auth_token=00702342-0000-1111-2222-c3e1500cafe1 HTTP/1.1 (status: HTTP/1.1 404 Not Found)

**Comment by Stories8106** [comment]
Works great!  Thanks for the quick turnaround.
