### ISSUE TITLE
Rush Bros does not unlock

### ISSUE THREAD

**Issue by cweiske** [ouya-saviors/ouya-game-data#171]
http://ouya.cweiske.de/game/com.Xyla.RushBros.htm
File: classic/com.Xyla.RushBros.json

**Comment by TheDreamMary** [comment]
This would be awesome if we could get the data.

**Comment by cweiske** [comment]
Added product with commit 43736c13be2f6d48449b443e69ed9a8cfc9b00b1

**Comment by cweiske** [comment]
The product unlock the game.
The main menu says "trial" after restarting the game, but inside play, the purchases menu item is greyed out and the levels are unlocked.
