### ISSUE TITLE
Ignis mortis revisit

### ISSUE THREAD

**Issue by MattiasKo** [ouya-saviors/ouya-game-data#182]
title: Ignis mortis revisited 2024
description: Play Ignis mortis, select a knight, berserker or archer to explore a world with the guidence of a map. Find all items and advance to the final boss and you win
Revisit 2024 Fixed bugs and now runs 60fps. Graphics of backgrounds and trees had to go. 
category: Platformer
players: 1
Main picture:
https://splattersoft.com/Ignis%20mortis%20revisited/Main.png
screenshots:
https://splattersoft.com/Ignis%20mortis%20revisited/ss01.png
https://splattersoft.com/Ignis%20mortis%20revisited/ss02.png
https://splattersoft.com/Ignis%20mortis%20revisited/ss03.png
https://splattersoft.com/Ignis%20mortis%20revisited/ss04.png
https://splattersoft.com/Ignis%20mortis%20revisited/ss05.png
https://splattersoft.com/Ignis%20mortis%20revisited/ss06.png

https://splattersoft.com/Ignis%20mortis%20revisited/Ignis%20mortis%20revisit.apk

**Comment by cweiske** [comment]
where is the .apk?

**Comment by MattiasKo** [comment]
I've updated the list.

**Comment by cweiske** [comment]
Thank you @MattiasKo - it's available on http://ouya.cweiske.de/discover/ now.
