### ISSUE TITLE
Add "Avenge myself"

### ISSUE THREAD

**Issue by cweiske** [ouya-saviors/ouya-game-data#185]
> A high-speed physics-based speedrunning FPS inspired by Tribes, Trackmania, and Sonic the Hedgehog. Master the movement, find your own routes through stages, and move like you've never moved before. 

https://madmanepic.itch.io/avenge-myself

**Comment by cweiske** [comment]
Problems:
- no entry in play menu
- no ouya icon

@MadmanEpic - could you please add those? See https://github.com/ouya-saviors/documentation/wiki/.apk-in-OUYA-games-menu

**Comment by MadmanEpic** [comment]
Should be taken care of now, the new version is up on the Itch page as "AVENGE MYSELF v1.0 (Ouya, Fixed)"

**Comment by cweiske** [comment]
All 3 games of the 2024 anniversary game jam have been added.
