### ISSUE TITLE
Order & Chaos crashes

### ISSUE THREAD

**Issue by cweiske** [ouya-saviors/ouya-game-data#186]
> hangman5950: I loaded order and chaos then when launched it tells me it has to install a gig, then once complete the game closes amd goes back to the game launch screen. Any idea?

https://discord.com/channels/581175002532151306/583081473398145037/1288487240393162836
https://ouya.cweiske.de/game/com.gameloft.android.OUYA.GloftMMOU.htm

**Comment by andiweli** [comment]
It seems the game servers have been shut down a few years ago by Gameloft. So the gamedata isn't available anymore.

**Comment by cweiske** [comment]
The game description already says so:
>  Technical notes: The servers have been shut down in 2023-02; the game does not work anymore.
