### ISSUE TITLE
Wraithborne does not unlock

### ISSUE THREAD

**Issue by cweiske** [ouya-saviors/ouya-game-data#188]
> Andiweli: Regarding the Ouya game „Wraithborne“ - it requires to buy the game in Level 3. The plain purchases plugin doesn‘t seem to work … Any idea if this game is playable?

**Comment by cweiske** [comment]
"God of Blades" worked once the plain purchases plugin was converted to a system app.

**Comment by andiweli** [comment]
Perhaps this helps here too :)

Tried to purchase with "unlock now" inside the game exactly at 21:02:10 (3 times).

**Comment by cweiske** [comment]
```
wraithborne_consumable_1
wraithborne_consumable_2
wraithborne_consumable_3
wraithborne_consumable_4
wraithborne_consumable_5
wraithborne_entitlement_1
wraithborne_entitlement_2
```

@andiweli - how are the products called, how much do they cost?

**Comment by cweiske** [comment]
The products returned by the server must be in the exact order as requested by the game - entitlements last. This is the first time I saw this behavior.

**Comment by cweiske** [comment]
@andiweli The gems can be bought. I don't know what entitlements you can buy; maybe you'll find out while playing the game.

**Comment by andiweli** [comment]
Both works :) Thanks!
Buying gems (for upgrading weapons and others) as well as buying the complete game.
Fantastic!

**Comment by cweiske** [comment]
What did it show when it asked to buy the full game? Currently I have "FIXME" as product title, which is obviously wrong.

**Comment by andiweli** [comment]
as i remember something like "want to buy the full game?"
