### ISSUE TITLE
Alien vs. Predator: Products missing

### ISSUE THREAD

**Issue by cweiske** [ouya-saviors/ouya-game-data#189]
> Andiweli: AvP seems to be all levels already, I only can‘t buy those crystals to buy better helmets and so

**Comment by andiweli** [comment]
Here are the times I clicked on the items... hope this helps investigating it further.

13:28 Item with 700.000 xeno points
13:29 Item with 200.000 xeno points
13:30 Item with 90.000 xeno points
13:31 Item with 40.000 xeno points

**Comment by cweiske** [comment]
Keys:
```
com_fde_avpevolution_avp_p1_0bonus
com_fde_avpevolution_avp_p2_10bonus
com_fde_avpevolution_avp_p3_25bonus
com_fde_avpevolution_avp_p4_75bonus
```
