### ISSUE TITLE
Vector in app purchases not possible

### ISSUE THREAD

**Issue by andiweli** [ouya-saviors/ouya-game-data#191]
Another game. Vector, a futuristic jump & run & action... or so :)
It has in app purchasement as well as an "upgrade to deluxe version".

In app coins are available...

- 25.000 coins for 4.99 USD
- 15.000 coins for 2.99 USD
- 10.000 coins for 1.99 USD
- 5.000 coins for 0.99 USD

I tried purchasing them today 10th of December...

- at 21:23:45 (25.000)
- at 21:24:15 (15.000)
- at 21:24:45 (10.000)
- at 21:25:15 (5.000)

Perhaps this helps investigating :)

Further there's an "upgrade to Deluxe version" which I clicked at 21:26:00 - but that only crashes the game and exits back to the launcher.

**Comment by cweiske** [comment]
```
coins_5000
coins_10000
coins_15000
coins_25000
full_version
```

**Comment by cweiske** [comment]
Products added.

**Comment by cweiske** [comment]
Deluxe version upgrade works here with the new products, too.

**Comment by andiweli** [comment]
Thank you! :)

Buying coins works as expected.
Buying deluxe version still crashes the game :(

**Comment by cweiske** [comment]
Related: #88
