### ISSUE TITLE
Purchase not working for God of Blades

### ISSUE THREAD

**Issue by Stories8106** [ouya-saviors/ouya-game-data#21]
In game purchase prompt indicates purchase was made, but doesn't actually complete the purchase in games.  On cweiske's server.

**Comment by cweiske** [comment]
Actively buying games will never work on my server because mine only has static (unchanging) responses to API requests. Responses to purchase requests needs to contain some data item of the request, and this is not possible statically.

Instead of needing an active purchase process, the game should start up, check if it has been bought on the server and see that is has been.

Some games have a "sync purchases" button. Maybe God of Blades has one, too.

**Comment by Stories8106** [comment]
Wouldn't this not work for the vast majority of games with in-app
purchases? Many games do not have the ability purchase the full version
from the store.

Or am I misunderstanding something?

**Comment by cweiske** [comment]
"check if it has been bought" does also work for in-app purchases. The game requests a list of "receipts" from the server and then looks which features have been bought and unlocks them.

**Comment by Stories8106** [comment]
So, to help me understand, the app needs to request "has it been purchased"
from your server, not making the purchase?

And at some point, the game should send that request?

**Comment by cweiske** [comment]
Correct.

I looked at the source of the game, and unlike others it only fetches the receipts when it gets a "android account changed" notification:

```
public class GodOfBlades extends Activity implements InputManager.InputDeviceListener {
    private BroadcastReceiver mAuthChangeReceiver = new BroadcastReceiver() {
        public void onReceive(Context context, Intent intent) {
            TestOuyaFacade test = IOuyaActivity.GetTestOuyaFacade();
            if (test != null) {
                test.requestReceipts();
            }
        }
    };

    public void onStart() {
        super.onStart();
        IntentFilter accountsChangedFilter = new IntentFilter();
        accountsChangedFilter.addAction("android.accounts.LOGIN_ACCOUNTS_CHANGED");
        registerReceiver(this.mAuthChangeReceiver, accountsChangedFilter);
    }
}
```

I currently do not know how to trigger this event.

**Comment by cweiske** [comment]
I built a dynamic purchase handler on my server, but the game does still not unlock - but also gives no more debug messages.

**Comment by cweiske** [comment]
I don't know why it does not unlock. Closing this for now.

**Comment by cweiske** [comment]
Found it! The purcase response must be encrypted twice.
