### ISSUE TITLE
Games list that do not function how they should

### ISSUE THREAD

**Issue by Omeric** [ouya-saviors/ouya-game-data#24]
Here is a game list that i have tried that give issues of some sort.  
there is a short description of the issue as well, including any error messages that were displayed:

# Radiant Defense
in game purchases dont work

> Purchase Failed

# Overkill 2
starts loading then crashes back to game launch page

# Tiamat X
crashes with error essage:
```
error inaction number 1
of async event: HTTP
for object
obj_GLOBAL_SCORE_CONTROLLER
data structure with index does not exist
at
gmlObject_obj_GLOBAL_SCORE_CON
```

# Marble Droid Classic
cannot purchase the full game (game is not automatically activated)

# Marble Droid 2
in game purchases do not work

# EnbornX
in game purchases do not work

# Shaddowgun
cannot purchase the full game:
> buy failed
> please check your internet connection and try later

# Beekyr
in game purchases do not work

# Pinball Arcade
in game purchases do not work

# Boomya!!
cannot unlock the full game

# Eliot Quest
crashes back to game launch page

# Hamster Hellstorm
cannot purchase the full game

----

Another thing that i noticed but not related to non functioning games:

Inferno 2 should not be under the role playing category in the discover section as its a dual stick shooter?

**Comment by cweiske** [comment]
- Pinball Arcade -> see #22

**Comment by cweiske** [comment]
I've removed "role playing" from inferno 2.

Closing since I opened new tickets for all other problems.
