### ISSUE TITLE
'Mussoumano Game' Purchases Not Available

### ISSUE THREAD

**Issue by Stories8106** [ouya-saviors/ouya-game-data#43]
Don't have high hopes for this one.  Looks like the shop options aren't available at all.  I think it might link to a store locally hosted. Might want to take a look.

On @cweiske server.

**Comment by cweiske** [comment]
Possible products:

moedas_001
moedas_002
moedas_005
moedas_003
esmeraldas_001
esmeraldas_002
esmeraldas_005
esmeraldas_003
desbloquear_visual
