### ISSUE TITLE
Proton Pulse does not activate with the unencrypted tickets exposed module

### ISSUE THREAD

**Issue by Omeric** [ouya-saviors/ouya-game-data#45]
Having the unencrypted tickets exposed module installed, proton pulse still goes into demo mode (buy scroller at the top of the screen during the menus)

When you click the buy button the purchase screen appears momentarily but then nothing happens and the game stays in demo mode.

Also proton pulse does not appear in the shop to download, it has to be sideloaded currently

**Comment by cweiske** [comment]
@Omeric Could you follow the instructions in https://github.com/ouya-saviors/ouya-game-data#games-in-demo-mode and check if the developer UUID is correct, and get the product ids from adb logcat?

**Comment by cweiske** [comment]
You did: cd48859974604c588e5340ef670f86ae853ad9a6

**Comment by cweiske** [comment]
Works fine.
