### ISSUE TITLE
Add full version of eXplosive Dinosaurs

### ISSUE THREAD

**Issue by cweiske** [ouya-saviors/ouya-game-data#5]
https://twitter.com/ExplosiveDinos/status/1143314484842434561

Unfortunately the download URL is broken: https://www.explosivedinosaurs.com/ouyadl/explosivedinosaurs-ouya-1.0.apk

**Comment by cweiske** [comment]
https://archive.org/details/ouya_com.rawrlab.explosivedinosaurs_1

**Comment by cweiske** [comment]
There will be a new version released soon: https://twitter.com/ExplosiveDinos/status/1200833375650697216

**Comment by Szeraax** [comment]
This file is already in IA. You just need to edit the gamedata to point to it: https://archive.org/download/ouya_com.rawrlab.explosivedinosaurs_1/Explosive%20Dinosaurs_1-unlocked_com.rawrlab.explosivedinosaurs.apk
